<?php

namespace ContainerASjZOuC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OMg25PBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OMg25PB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OMg25PB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CategorieController::add' => ['privates', '.service_locator.daCyYuT', 'get_ServiceLocator_DaCyYuTService', true],
            'App\\Controller\\CategorieController::hebergementByCategorie' => ['privates', '.service_locator.Sm2zpFN', 'get_ServiceLocator_Sm2zpFNService', true],
            'App\\Controller\\CommentaireController::delete' => ['privates', '.service_locator.5Tv0MEa', 'get_ServiceLocator_5Tv0MEaService', true],
            'App\\Controller\\CommentaireController::update' => ['privates', '.service_locator.5Tv0MEa', 'get_ServiceLocator_5Tv0MEaService', true],
            'App\\Controller\\ContactController::index' => ['privates', '.service_locator.uVvF4gL', 'get_ServiceLocator_UVvF4gLService', true],
            'App\\Controller\\HerbergementController::addHebergement' => ['privates', '.service_locator.2UiWjku', 'get_ServiceLocator_2UiWjkuService', true],
            'App\\Controller\\HerbergementController::allhebergements' => ['privates', '.service_locator.pL5.cRo', 'get_ServiceLocator_PL5_CRoService', true],
            'App\\Controller\\HerbergementController::delete' => ['privates', '.service_locator.ZR.4dc8', 'get_ServiceLocator_ZR_4dc8Service', true],
            'App\\Controller\\HerbergementController::oneProduct' => ['privates', '.service_locator.maYrWqd', 'get_ServiceLocator_MaYrWqdService', true],
            'App\\Controller\\HerbergementController::update' => ['privates', '.service_locator.2UiWjku', 'get_ServiceLocator_2UiWjkuService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.pL5.cRo', 'get_ServiceLocator_PL5_CRoService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.T9HfhLz', 'get_ServiceLocator_T9HfhLzService', true],
            'App\\Controller\\ReservationController::mesReservations' => ['privates', '.service_locator.jdxm4TC', 'get_ServiceLocator_Jdxm4TCService', true],
            'App\\Controller\\ReservationController::reserver' => ['privates', '.service_locator.hMVBymq', 'get_ServiceLocator_HMVBymqService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\SecurityController::passerEnAdmin' => ['privates', '.service_locator.bYqs9Eo', 'get_ServiceLocator_BYqs9EoService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.sYrpthU', 'get_ServiceLocator_SYrpthUService', true],
            'App\\Controller\\UserController::editPassword' => ['privates', '.service_locator.P63wSpt', 'get_ServiceLocator_P63wSptService', true],
            'App\\Controller\\UserController::editPhoto' => ['privates', '.service_locator.j.xg0Ku', 'get_ServiceLocator_J_Xg0KuService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\CategorieController:add' => ['privates', '.service_locator.daCyYuT', 'get_ServiceLocator_DaCyYuTService', true],
            'App\\Controller\\CategorieController:hebergementByCategorie' => ['privates', '.service_locator.Sm2zpFN', 'get_ServiceLocator_Sm2zpFNService', true],
            'App\\Controller\\CommentaireController:delete' => ['privates', '.service_locator.5Tv0MEa', 'get_ServiceLocator_5Tv0MEaService', true],
            'App\\Controller\\CommentaireController:update' => ['privates', '.service_locator.5Tv0MEa', 'get_ServiceLocator_5Tv0MEaService', true],
            'App\\Controller\\ContactController:index' => ['privates', '.service_locator.uVvF4gL', 'get_ServiceLocator_UVvF4gLService', true],
            'App\\Controller\\HerbergementController:addHebergement' => ['privates', '.service_locator.2UiWjku', 'get_ServiceLocator_2UiWjkuService', true],
            'App\\Controller\\HerbergementController:allhebergements' => ['privates', '.service_locator.pL5.cRo', 'get_ServiceLocator_PL5_CRoService', true],
            'App\\Controller\\HerbergementController:delete' => ['privates', '.service_locator.ZR.4dc8', 'get_ServiceLocator_ZR_4dc8Service', true],
            'App\\Controller\\HerbergementController:oneProduct' => ['privates', '.service_locator.maYrWqd', 'get_ServiceLocator_MaYrWqdService', true],
            'App\\Controller\\HerbergementController:update' => ['privates', '.service_locator.2UiWjku', 'get_ServiceLocator_2UiWjkuService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.pL5.cRo', 'get_ServiceLocator_PL5_CRoService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.T9HfhLz', 'get_ServiceLocator_T9HfhLzService', true],
            'App\\Controller\\ReservationController:mesReservations' => ['privates', '.service_locator.jdxm4TC', 'get_ServiceLocator_Jdxm4TCService', true],
            'App\\Controller\\ReservationController:reserver' => ['privates', '.service_locator.hMVBymq', 'get_ServiceLocator_HMVBymqService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\SecurityController:passerEnAdmin' => ['privates', '.service_locator.bYqs9Eo', 'get_ServiceLocator_BYqs9EoService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.sYrpthU', 'get_ServiceLocator_SYrpthUService', true],
            'App\\Controller\\UserController:editPassword' => ['privates', '.service_locator.P63wSpt', 'get_ServiceLocator_P63wSptService', true],
            'App\\Controller\\UserController:editPhoto' => ['privates', '.service_locator.j.xg0Ku', 'get_ServiceLocator_J_Xg0KuService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\CategorieController::add' => '?',
            'App\\Controller\\CategorieController::hebergementByCategorie' => '?',
            'App\\Controller\\CommentaireController::delete' => '?',
            'App\\Controller\\CommentaireController::update' => '?',
            'App\\Controller\\ContactController::index' => '?',
            'App\\Controller\\HerbergementController::addHebergement' => '?',
            'App\\Controller\\HerbergementController::allhebergements' => '?',
            'App\\Controller\\HerbergementController::delete' => '?',
            'App\\Controller\\HerbergementController::oneProduct' => '?',
            'App\\Controller\\HerbergementController::update' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\ReservationController::mesReservations' => '?',
            'App\\Controller\\ReservationController::reserver' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SecurityController::passerEnAdmin' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::editPassword' => '?',
            'App\\Controller\\UserController::editPhoto' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CategorieController:add' => '?',
            'App\\Controller\\CategorieController:hebergementByCategorie' => '?',
            'App\\Controller\\CommentaireController:delete' => '?',
            'App\\Controller\\CommentaireController:update' => '?',
            'App\\Controller\\ContactController:index' => '?',
            'App\\Controller\\HerbergementController:addHebergement' => '?',
            'App\\Controller\\HerbergementController:allhebergements' => '?',
            'App\\Controller\\HerbergementController:delete' => '?',
            'App\\Controller\\HerbergementController:oneProduct' => '?',
            'App\\Controller\\HerbergementController:update' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\ReservationController:mesReservations' => '?',
            'App\\Controller\\ReservationController:reserver' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SecurityController:passerEnAdmin' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:editPassword' => '?',
            'App\\Controller\\UserController:editPhoto' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
