<?php

namespace ContainerASjZOuC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHerbergementService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.hMVBymq.App\Entity\Herbergement' shared service.
     *
     * @return \App\Entity\Herbergement
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.hMVBymq": it needs an instance of "App\\Entity\\Herbergement" but this type has been excluded in "config/services.yaml".');
    }
}
