<?php

namespace Container8wxDNiv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZR_4dc8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZR.4dc8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZR.4dc8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repo' => ['privates', 'App\\Repository\\HerbergementRepository', 'getHerbergementRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\HerbergementRepository',
        ]);
    }
}
