<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_categorie_add' => [[], ['_controller' => 'App\\Controller\\CategorieController::add'], [], [['text', '/add_categorie']], [], [], []],
    'app_hebergement_categorie' => [['slug'], ['_controller' => 'App\\Controller\\CategorieController::hebergementByCategorie'], [], [['variable', '/', '[^/]++', 'slug', true], ['text', '/hebergement/categorie']], [], [], []],
    'app_commentaire_modifier' => [['id'], ['_controller' => 'App\\Controller\\CommentaireController::update'], [], [['variable', '_', '[^/]++', 'id', true], ['text', '/modifier_commentaire']], [], [], []],
    'app_commentaire_supprimer' => [['id'], ['_controller' => 'App\\Controller\\CommentaireController::delete'], [], [['variable', '_', '[^/]++', 'id', true], ['text', '/supprimer_commentaire']], [], [], []],
    'app_contact' => [[], ['_controller' => 'App\\Controller\\ContactController::index'], [], [['text', '/contact']], [], [], []],
    'app_hebergement_add' => [[], ['_controller' => 'App\\Controller\\HerbergementController::addHebergement'], [], [['text', '/add_hebergement']], [], [], []],
    'app_hebergements' => [[], ['_controller' => 'App\\Controller\\HerbergementController::allhebergements'], [], [['text', '/hebergements']], [], [], []],
    'app_hebergement' => [['id'], ['_controller' => 'App\\Controller\\HerbergementController::oneProduct'], [], [['variable', '_', '[^/]++', 'id', true], ['text', '/hebergement']], [], [], []],
    'app_hebergement_update' => [['id'], ['_controller' => 'App\\Controller\\HerbergementController::update'], ['id' => '\\d+'], [['variable', '_', '\\d+', 'id', true], ['text', '/update_hebergement']], [], [], []],
    'app_hebergement_delete' => [['id'], ['_controller' => 'App\\Controller\\HerbergementController::delete'], ['id' => '\\d+'], [['variable', '_', '\\d+', 'id', true], ['text', '/delete_hebergement']], [], [], []],
    'app_home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'app_mention' => [[], ['_controller' => 'App\\Controller\\MentionController::index'], [], [['text', '/mention']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'reservation_reserver' => [['id'], ['_controller' => 'App\\Controller\\ReservationController::reserver'], [], [['text', '/reserver'], ['variable', '/', '[^/]++', 'id', true], ['text', '/hebergement']], [], [], []],
    'app_mes_reservations' => [[], ['_controller' => 'App\\Controller\\ReservationController::mesReservations'], [], [['text', '/mes-reservations']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
    'app_passer_en_admin' => [['id'], ['_controller' => 'App\\Controller\\SecurityController::passerEnAdmin'], ['id' => '\\d+'], [['variable', '-', '\\d+', 'id', true], ['text', '/passer-en-admin']], [], [], []],
    'user.edit' => [['id'], ['_controller' => 'App\\Controller\\UserController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/user/edition']], [], [], []],
    'user.edit.password' => [['id'], ['_controller' => 'App\\Controller\\UserController::editPassword'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/user/edition-mot-de-passe']], [], [], []],
    'app_mon_profil' => [[], ['_controller' => 'App\\Controller\\UserController::showProfile'], [], [['text', '/profil']], [], [], []],
    'user.edit.photo' => [['id'], ['_controller' => 'App\\Controller\\UserController::editPhoto'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/user/edition-photo']], [], [], []],
];
